name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./test/docker-compose.yml"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn
      - run: yarn test-ci
