name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./test/docker-compose.yml"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm i
      - run: npm run test-ci
